const userController = require('./userController');
const eventController = require('./eventController');
const donatesController = require('./donatesController');
const dontationController = require('./donationController');
const programController = require('./programController');
const hostsController = require('./hostsController');
const needsController = require('./needsController');
const volunteersController = require('./contributesController');
/*
 * This file was autogenerated by sequelize.
 */

module.exports = {
  userController,
  eventController,
  donatesController,
  dontationController,
  programController,
  hostsController,
  needsController,
  volunteersController
};
